# Generated by Django 4.1.7 on 2023-03-12 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0004_devicelog_company'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'Company'},
        ),
        migrations.AlterModelOptions(
            name='device',
            options={'verbose_name_plural': 'Device'},
        ),
        migrations.AlterModelOptions(
            name='devicelog',
            options={'verbose_name_plural': 'Device Log'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name_plural': 'Employee'},
        ),
    ]
